### ISSUE TITLE
Bot doesn't respond to commands on some servers?

### ISSUE THREAD

**Issue by ali6836** [Darthfett/helperbot#45]
I am trying to use the bot on play.corbacraftmc.com but it is not following any commands?

**Comment by Darthfett** [comment]
Is that a bukkit/forge server?  It looks like they have mods installed, which helperbot does not attempt to support.  I'm going to close this issue, but if this is not the case, please feel free to reopen.

If you would like to contribute, I will accept changes to support other types of servers, as long as they don't affect the ability to support Vanilla servers, or greatly affect maintainability.
